services:
  med_diff_models:
    build: .
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    environment:
      - MY_MODELS_PATH="/app/src/my_models"
      - DATASETS_DIR_PATH=${DATASETS_DIR_PATH}
    volumes:
      - /app/datasets/:${DATASETS_DIR_PATH}:ro