services:
  med_diff_models:
    build: .
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    environment:
      - MY_MODELS_PATH=/app/src/my_models
    volumes:
      - ${DATASETS_DIR_PATH}:/app/datasets/:rw